# Generated by Django 5.0.6 on 2024-06-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PICKUP_CITY_STATE', models.CharField(max_length=255)),
                ('DELIVERY_CITY_STATE', models.CharField(max_length=255)),
                ('PICKUP_DATE', models.DateField()),
                ('LENGTH', models.CharField(max_length=10)),
                ('WEIGHT', models.CharField(max_length=10)),
                ('DELIVERY_DATE', models.DateField()),
                ('REFERENCE_LOAD_NUMBER', models.CharField(max_length=255)),
                ('COMMODITY', models.CharField(max_length=255)),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TYPE', models.CharField(default='Dry Van', max_length=50)),
                ('FTL_LTL', models.CharField(default='FTL', max_length=3)),
                ('NAME', models.CharField(max_length=255)),
                ('CONTACT', models.CharField(max_length=255)),
                ('LOAD_DESCRIPTION', models.TextField()),
            ],
        ),
    ]
