# Generated by Django 5.0.6 on 2024-06-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_commodity_load_commodity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
