# Generated by Django 5.0.6 on 2024-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_load_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
