# Generated by Django 5.0.6 on 2024-06-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_load_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='ftl_ltl',
            field=models.CharField(blank=True, default='FTL', max_length=3, null=True),
        ),
    ]
