# Generated by Django 5.0.6 on 2024-06-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_alter_load_ftl_ltl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='delivery_city_state',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='load',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='load',
            name='ftl_ltl',
        ),
        migrations.RemoveField(
            model_name='load',
            name='load_description',
        ),
        migrations.RemoveField(
            model_name='load',
            name='pickup_city_state',
        ),
        migrations.RemoveField(
            model_name='load',
            name='reference_load_number',
        ),
        migrations.RemoveField(
            model_name='load',
            name='type',
        ),
        migrations.AddField(
            model_name='load',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='comment',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='contact_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='dh_d',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='dh_o',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='dlv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='load',
            name='ref_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='results_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='results_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='suggested_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='to_dlv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='truck_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='commodity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
